[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--legacy-peer-deps"  # Add npm install flag

[context.production.environment]
  NPM_FLAGS = "--legacy-peer-deps" 

[build]
  command = "npm i --legacy-peer-deps && npm run build"
  publish = "build"  # Path to your publish directory, e.g., 'build' for React
